export {default as Piece} from "./Piece"
export {WPawn as WPawn} from "./Pawn"
export {BPawn as BPawn} from "./Pawn"
export {default as Rook} from "./Rook"
export {default as Bishop} from "./Bishop"
export {default as Knight} from "./Knight"
export {default as Queen} from "./Queen"
export {default as King} from "./King"